### ISSUE TITLE
npm-container is not compatible with architecture 'os.linux.x86_64'

### ISSUE THREAD

**Issue by imkost** [thereactivestack/kickstart-simple#18]
When I add Radium (npm package) to `packages.json` and then deploy application via `mupx`, I get this error:

```plain
Errors prevented bundling:
While linking the program:
error: npm-container is not compatible with architecture 'os.linux.x86_64'
```

I tried another webpack approach https://github.com/jedwards1211/meteor-webpack-react. I added same version of Radium (0.14.1) and used `mupx`. The project was deployed successfully.

**Comment by eXon** [comment]
I'm using mup and it is automatically fixing this issue. I was pretty sure the next version would too. Have you tried the older version?

Maybe we should split the NPM packages that are needed on the server and those that we only need with Webpack. You don't need to deploy Radium npm package to the server because it is bundled in your application by Webpack. If you were using phantomjs or things like that, it would be another story.

Maybe webpack could use a webpack.packages.json. It would be cleaner.

**Comment by eXon** [comment]
Maybe I could create a webpack:npm package that would be a fork to meteorhacks:npm, set a different file and have them only available on build time.

**Comment by eXon** [comment]
You can now use webpack.packages.json and it will not get bundled with your app and sent to the server. I'm pretty sure the NPM package that was causing you trouble with this was not something you needed to execute on the server.

I'm closing this but if you still have troubles, let me know.

**Comment by eXon** [comment]
BTW I posted on Meteor forums about it: https://forums.meteor.com/t/webpack-compiler-inside-meteor-es6-modules-hot-reload-and-code-splitting/11264/124?u=benoitt

**Comment by imkost** [comment]
I tried mup instead of mupx, but I had some troubles (errors in console) with this. Those errors were not kickstart-related, but my server related.

I've just updated to 0.2 and everything is cool now. `mupx` is working, npm packages installation is now fast.

Thank you!

**Comment by tomitrescak** [comment]
Fantastic! One thing is not clear though, how does the pack know when it is in production mode?

**Comment by eXon** [comment]
when you run it with --production or when you build it. Right now I might be missing a few use cases but I have a PR with Meteor to have the real info passed to the compiler
