### ISSUE TITLE
Question: Webpack with packages structured app

### ISSUE THREAD

**Issue by nagelflorian** [thereactivestack/kickstart-simple#3]
I've been using the ['Package for everything'](http://howwedoapps.com/2015/07/16/how-i-develop-meteorjs-apps-part1) structure and was wondering what your recommended way of using Webpack with this approach is.

When I add a package to kickstart-simple and create a new component like so:

```js
import { Component, PropTypes } from 'react';

export default class Demo extends Component {
  render() {
  	return <h1>Demo</h1>
  }
}
```

I get this error message:

```
... 'import' and 'export' may only appear at the top level
```

**Comment by eXon** [comment]
The reason is because your packages are all compiled individually and webpack is not setup inside of them. This syntax is not supported in regular Meteor.

The reason of using smart packages was mainly to have a greater control over load order. But with webpack this problem is solved. You can just create folders inside your global projects.

I am trying to figure out a way of making smart packages work, but I don't know if this is really useful  with Webpack. I will be looking into that. But it is not simple because how packages are all independants.
